
version: 1.0.{branch}-{build}

image: Visual Studio 2015

clone_depth: 5

skip_tags: true

configuration:
  - Release
  - Debug

platform:
  - x64

environment:
  matrix:
   - PROFILE: MSVC2015
     CMAKE_GENERATOR: "Ninja"
     CMAKE_OPTIONS: "-DBUILD_SAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_GL32=OFF -DBUILD_VULKAN=OFF"

install:
  - set "CLONE_DIR=swiftshader"
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\temp;%PATH%"
  - '"C:\Program Files\Git\bin\sh.exe" --login 1-install-deps-appveyor.sh'
  - refreshenv
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set "CLONE_DIR=swiftshader"
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\temp;%PATH%"
  - set "GITHUB_USER=paulthomson"
  - set "GITHUB_REPO=build-swiftshader"
  - set "COMMIT_ID=%APPVEYOR_REPO_COMMIT%"
  - set "GROUP_DOTS=github.%GITHUB_USER%"
  - set "GROUP_SLASHES=github/%GITHUB_USER%"
  - set "ARTIFACT=%GITHUB_REPO%"
  - set "VERSION=%COMMIT_ID%"
  - set "POM_FILE=%GITHUB_REPO%-%VERSION%.pom"
  - set "TAG=%GROUP_SLASHES%/%ARTIFACT%/%VERSION%"
  - set "CMAKE_BUILD_TYPE=%Configuration%"
  - set "CLASSIFIER=Windows_x64_%CMAKE_BUILD_TYPE%"
  - set "INSTALL_DIR=%ARTIFACT%-%VERSION%-%CLASSIFIER%"

build_script:
  - '"C:\Program Files\Git\bin\sh.exe" --login 2-build-appveyor.sh'

on_success:
  - '"C:\Program Files\Git\bin\sh.exe" --login 3-release-appveyor.sh'

